---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm config set spin false
  - phantomjs --version

install:
  - npm install

script:
  - npm test
