---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - phantomjs --version

install:
  - yarn install

script:
  - yarn test
